//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment_time
    {
        public long assignment_id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
        public long assignment_time_id { get; set; }
        public string description { get; set; }
    
        public virtual assignment assignment { get; set; }
    }
}
