//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class security_level
    {
        public long security_level_id { get; set; }
        public string secrity_level { get; set; }
    
        public virtual security_level security_level1 { get; set; }
        public virtual security_level security_level2 { get; set; }
    }
}
