//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataContracts.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public assignment()
        {
            this.assignment_time = new HashSet<assignment_time>();
        }
    
        public long assignment_id { get; set; }
        public long project_id { get; set; }
        public long employee_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public long role_id { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        public virtual project project { get; set; }
        public virtual role role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignment_time> assignment_time { get; set; }
    }
}
